### ISSUE TITLE
Official Linux release

### ISSUE THREAD

**Issue by rowanjacobs** [sclevine/yj#1]
We'd like to use this in a concourse pipeline with a Docker image that doesn't have golang installed. Unfortunately, this is really hard to do, because the only official release binary is for OS X!

**Comment by sclevine** [comment]
Thanks for pointing this out, will do.

FYI, you could use a multi-stage Dockerfile to build it in the meantime:
```
ARG go_version=1.10.1
FROM golang:$go_version as build
RUN go get github.com/sclevine/yj

FROM myimage
COPY --from=build /go/bin /usr/local/bin
```

**Comment by sclevine** [comment]
Done.

FYI, avoid using the `-c` option (candiedyaml is no longer maintained, so it will be removed soon) and the `-y` option (this will change meaning when I add support for TOML).

**Comment by sclevine** [comment]
v2.0 is out with support for TOML. The interface should remain stable now.
