### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by jmooring** [sclevine/yj#19]
```
go get github.com/sclevine/yj
```

```
go: downloading github.com/sclevine/yj v0.0.0-20200815061347-554173e71934
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading github.com/pelletier/go-toml v1.8.0
go: downloading gopkg.in/yaml.v3 v3.0.0-20200615113413-eeeca48fe776
# github.com/sclevine/yj/toml
../go/pkg/mod/github.com/sclevine/yj@v0.0.0-20200815061347-554173e71934/toml/encoder.go:63:7: tree.SetPositionPath undefined (type *toml.Tree has no field or method SetPositionPath)
../go/pkg/mod/github.com/sclevine/yj@v0.0.0-20200815061347-554173e71934/toml/encoder.go:79:6: tree.SetPositionPath undefined (type *toml.Tree has no field or method SetPositionPath)
```

[go version go1.16.3 linux/amd64]

**Comment by sclevine** [comment]
Apologies, as a workaround you can clone the repo and build with `go build`. See: https://github.com/golang/go/issues/30354

I used a `replace` directive in `go.mod` as a stopgap, while waiting for https://github.com/pelletier/go-toml/pull/426 to merge. It's no longer necessary, and I plan to bump yj to go-toml v1.9.0 (and thus TOML v1.0.0-rc.3) soon.

**Comment by jmooring** [comment]
Resolved with https://github.com/sclevine/yj/commit/737bdf40a5d1f3935acdce0b7e67cc53d7240e28. Thanks.
