### ISSUE TITLE
Failed to parse escaped quote in TOML

### ISSUE THREAD

**Issue by oxalica** [sclevine/yj#20]
I have a toml file:
```toml
["\"foo\""]
"\"bar\"" = "\"baz\""
```

`yj -tj <a.toml` failed with:
```
Error parsing TOML: (1, 2): invalid table array key: invalid bare key character: \
```

According to the TOML specification:
- The escape `\"` is valid in basic strings. (https://toml.io/en/v0.5.0#string)
- Quoted keys follow the exact same rules as either basic strings or literal strings. (https://toml.io/en/v0.5.0#keys)
- Naming rules for tables are the same as for keys. (https://toml.io/en/v0.5.0#table)

**Comment by sclevine** [comment]
Thanks for the report!

This was due to an upstream issue: https://github.com/pelletier/go-toml/issues/427
It is fixed in v5.1.0, by switching to https://github.com/BurntSushi/toml
