### ISSUE TITLE
go get github.com/sclevine/yj@v5.0.0 gives invalid version

### ISSUE THREAD

**Issue by prakkarp** [sclevine/yj#22]
% go get github.com/sclevine/yj@v5.0.0
go get: github.com/sclevine/yj@v5.0.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v5

**Comment by sclevine** [comment]
Should work now, but note that the major version must be specified in the path:
```
go get github.com/sclevine/yj/v5@v5.1.0
```
