### ISSUE TITLE
`yj -v` reports v0.0.0

### ISSUE THREAD

**Issue by FunctionalHacker** [sclevine/yj#32]
I have added the `yj` package in the Arch Linux User Repository (AUR). The package builds fine but the resulting binary will report `v0.0.0` as it's version. Any way to fix this?

You can review the PKGBUILD here https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=yj

**Comment by sclevine** [comment]
Hey, thanks for helping out!

See the homebrew formula for reference:
https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/yj.rb

Instead of:
```
go build -race
```
use:
```
go build -ldflags "-X main.Version=$pkgver"
```
(`-race` will slow down execution of yj considerably and use more memory)

**Comment by FunctionalHacker** [comment]
Thanks a lot, I got it working!
