### ISSUE TITLE
distribute over brew for macos

### ISSUE THREAD

**Issue by jasonkuhrt** [sclevine/yj#5]
Great tool, good job, and many thanks!

Being able to `brew install yj` would be a nice-to-have. Open to this?

**Comment by sclevine** [comment]
It's on my list, but my list is long. 😄 

Would you be open to contributing a yj formula to homebrew-core?

**Comment by jasonkuhrt** [comment]
Cool. Yep totally open, but also a long list :D This would be a nice opportunity to learn how to do this too. If I can find the time I'll give it a shot or else maybe someone else will get to it first.

**Comment by sclevine** [comment]
This seems to work with `brew install yj.rb`:
```ruby
require "language/go"

class Yj < Formula
  desc "CLI to convert between YAML, TOML, JSON, and HCL."
  homepage "https://github.com/sclevine/yj"

  url "https://github.com/sclevine/yj/archive/v4.0.0.tar.gz"
  sha256 "8423486cdc0f6bd912bdcb9f61ef89427a70b094352c45e62b1343c9b2ea92f4"
  head "https://github.com/sclevine/yj"

  depends_on "go" => :build

  def install
    system "go", "build", "-o", bin/"yj", "."
  end

  test do
    assert_match '{"a":1}', shell_output("echo a=1|#{bin}/yj -t", 0)
  end
end
```
My local homebrew install appears to be too broken to run `brew audit`, and the [Acceptable Formulae](https://docs.brew.sh/Acceptable-Formulae) criteria discourage authors from submitting their own work. Feel free to PR this to homebrew-core if you'd like to.

**Comment by paw-lu** [comment]
Is `brew install jy.rb` recommended way to install via brew? Could I add this command to `README.md` is it is?

**Comment by sclevine** [comment]
Finally got around to this: https://github.com/Homebrew/homebrew-core/pull/58620

**Comment by sclevine** [comment]
Merged: `brew install yj`
